CREATE TABLE IF NOT EXISTS smx_assist_devices (
    id BIGINT NOT NULL AUTO_INCREMENT,
    id_empresa INT NOT NULL,
    id_login INT NOT NULL,
    login_name VARCHAR(120) DEFAULT NULL,
    user_name VARCHAR(180) DEFAULT NULL,
    company_name VARCHAR(190) DEFAULT NULL,
    device_uuid CHAR(36) NOT NULL,
    device_name VARCHAR(190) NOT NULL,
    host_name VARCHAR(190) DEFAULT NULL,
    platform VARCHAR(40) NOT NULL,
    platform_version VARCHAR(80) DEFAULT NULL,
    architecture VARCHAR(40) DEFAULT NULL,
    agent_version VARCHAR(50) DEFAULT NULL,
    agent_channel VARCHAR(20) DEFAULT NULL,
    device_public_key TEXT DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'offline',
    ip_public VARCHAR(64) DEFAULT NULL,
    ip_local VARCHAR(64) DEFAULT NULL,
    last_seen_at DATETIME DEFAULT NULL,
    registered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_device_uuid (device_uuid),
    KEY idx_empresa_status (id_empresa, status, last_seen_at),
    KEY idx_login (id_login),
    KEY idx_platform (platform)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS smx_assist_device_capabilities (
    id BIGINT NOT NULL AUTO_INCREMENT,
    device_id BIGINT NOT NULL,
    can_screen_capture TINYINT(1) NOT NULL DEFAULT 0,
    can_input_control TINYINT(1) NOT NULL DEFAULT 0,
    can_file_transfer TINYINT(1) NOT NULL DEFAULT 0,
    can_clipboard_sync TINYINT(1) NOT NULL DEFAULT 0,
    can_audio_stream TINYINT(1) NOT NULL DEFAULT 0,
    can_unattended TINYINT(1) NOT NULL DEFAULT 0,
    requires_local_consent TINYINT(1) NOT NULL DEFAULT 1,
    permissions_screen TINYINT(1) NOT NULL DEFAULT 0,
    permissions_accessibility TINYINT(1) NOT NULL DEFAULT 0,
    permissions_input_monitoring TINYINT(1) NOT NULL DEFAULT 0,
    raw_payload JSON DEFAULT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_device_caps (device_id),
    CONSTRAINT fk_assist_caps_device FOREIGN KEY (device_id) REFERENCES smx_assist_devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS smx_assist_requests (
    id BIGINT NOT NULL AUTO_INCREMENT,
    id_empresa INT NOT NULL,
    id_login INT NOT NULL,
    login_name VARCHAR(120) DEFAULT NULL,
    user_name VARCHAR(180) DEFAULT NULL,
    source_device_id BIGINT DEFAULT NULL,
    request_type VARCHAR(30) NOT NULL DEFAULT 'remote_support',
    platform VARCHAR(40) DEFAULT NULL,
    app_version VARCHAR(50) DEFAULT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'normal',
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    notes TEXT DEFAULT NULL,
    taken_by_login INT DEFAULT NULL,
    taken_by_name VARCHAR(180) DEFAULT NULL,
    resolved_by_login INT DEFAULT NULL,
    resolved_by_name VARCHAR(180) DEFAULT NULL,
    resolution_notes TEXT DEFAULT NULL,
    taken_at DATETIME DEFAULT NULL,
    resolved_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_empresa_status (id_empresa, status, created_at),
    KEY idx_login_status (id_login, status, created_at),
    KEY idx_taken (taken_by_login, status),
    CONSTRAINT fk_assist_request_device FOREIGN KEY (source_device_id) REFERENCES smx_assist_devices(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS smx_assist_sessions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_id BIGINT DEFAULT NULL,
    id_empresa INT NOT NULL,
    support_login_id INT NOT NULL,
    support_login_name VARCHAR(180) DEFAULT NULL,
    target_device_id BIGINT NOT NULL,
    mode VARCHAR(20) NOT NULL DEFAULT 'assisted',
    status VARCHAR(20) NOT NULL DEFAULT 'created',
    started_at DATETIME DEFAULT NULL,
    ended_at DATETIME DEFAULT NULL,
    duration_sec INT DEFAULT NULL,
    consent_required TINYINT(1) NOT NULL DEFAULT 1,
    consent_granted_at DATETIME DEFAULT NULL,
    recording_enabled TINYINT(1) NOT NULL DEFAULT 0,
    recording_path VARCHAR(255) DEFAULT NULL,
    transport_type VARCHAR(20) DEFAULT NULL,
    relay_used TINYINT(1) NOT NULL DEFAULT 0,
    close_reason VARCHAR(40) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_empresa_status (id_empresa, status, created_at),
    KEY idx_support (support_login_id, status),
    KEY idx_device (target_device_id, status),
    CONSTRAINT fk_assist_session_request FOREIGN KEY (request_id) REFERENCES smx_assist_requests(id) ON DELETE SET NULL,
    CONSTRAINT fk_assist_session_device FOREIGN KEY (target_device_id) REFERENCES smx_assist_devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS smx_assist_session_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    session_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_level VARCHAR(20) NOT NULL DEFAULT 'info',
    actor_type VARCHAR(20) DEFAULT NULL,
    actor_login_id INT DEFAULT NULL,
    payload JSON DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_session_time (session_id, created_at),
    KEY idx_event_type (event_type, created_at),
    CONSTRAINT fk_assist_event_session FOREIGN KEY (session_id) REFERENCES smx_assist_sessions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS smx_assist_policies (
    id BIGINT NOT NULL AUTO_INCREMENT,
    id_empresa INT NOT NULL,
    allow_unattended TINYINT(1) NOT NULL DEFAULT 0,
    require_consent TINYINT(1) NOT NULL DEFAULT 1,
    allow_file_transfer TINYINT(1) NOT NULL DEFAULT 1,
    allow_clipboard_sync TINYINT(1) NOT NULL DEFAULT 1,
    record_sessions TINYINT(1) NOT NULL DEFAULT 1,
    allowed_support_roles JSON DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_empresa_policy (id_empresa)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS smx_assist_agent_tokens (
    id BIGINT NOT NULL AUTO_INCREMENT,
    device_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    token_scope VARCHAR(50) NOT NULL DEFAULT 'agent',
    expires_at DATETIME NOT NULL,
    revoked_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_token_hash (token_hash),
    KEY idx_device_expires (device_id, expires_at),
    CONSTRAINT fk_assist_token_device FOREIGN KEY (device_id) REFERENCES smx_assist_devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS smx_assist_bootstrap_tokens (
    id BIGINT NOT NULL AUTO_INCREMENT,
    id_empresa INT NOT NULL,
    id_login INT NOT NULL,
    login_name VARCHAR(120) DEFAULT NULL,
    user_name VARCHAR(180) DEFAULT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    used_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_token_hash (token_hash),
    KEY idx_empresa_expires (id_empresa, expires_at),
    KEY idx_login_expires (id_login, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
